# Base de datos local
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/coctel_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:admin}

spring.jpa.show-sql=true

# Frontend
app.frontend-url=http://localhost:5173

# CORS
app.allowed-origins=${APP_ALLOWED_ORIGINS:http://localhost:5173}
